spring:
  application:
    name: Flight_Inventory_Service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5433/gatewaydb
#    username: gateway
#    password: gateway
#    driverClassName: org.postgresql.Driver


          
server:
   port: 8080
   
jwt:
  secret: Secret-key
  jwtExpirationMs: 300000 # 5 minutes duration: 5 minutes * 60 seconds * 1000 miliseconds
  jwtRefreshExpirationMs: 604800000 # 7 days
  

      
